Munchkin Online/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Web.WebPages.OAuth;
using Munchkin_Online.Core.Auth;
using Munchkin_Online.Core.Database;
using Munchkin_Online.Models;
using Ninject;
using Munchkin_Online.Core.Notifications;

namespace Munchkin_Online.Controllers
{
    public class AccountsController : Controller
    {
        [Inject]
        public IAuthentication Auth { get; set; }

        public User CurrentUser
        {
            get
            {
                return ((UserIndentity)(Auth.CurrentUser.Identity)).User;
            }
        }

        UserRepository Users = new UserRepository();

        public ActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public ActionResult Register()
        {
            if (CurrentUser == null)
                return View();
            else
                return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult Register(RegisterModel reg)
        {
            if (CurrentUser == null)
            {
                if (ModelState.IsValid)
                {
                    var user = new User();
                    user.Email = reg.Email;
                    user.Nickname = reg.Nickname;
                    user.PasswordHash = reg.Password;
                    user.LastActivity = DateTime.Now;
                    if (Users.Add(user) == false)
                        return View(reg);
                    else
                        return RedirectToAction("Index", "Home");
                }
                else
                    return View(reg);
            }
            else
                return RedirectToAction("Index", "Home");
        }

        public ActionResult Logout()
        {
            Auth.LogOut();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginModel m)
        {
            if (ModelState.IsValid)
            {
                if (Auth.Login(m.Email, m.Password) != null)
                    return RedirectToAction("Index", "Home");
                else
                    return View();
            }
            else
                return View();

        }

        [AllowAnonymous]
        public void VKLogin()
        {
            OAuthWebSecurity.RequestAuthentication("VK", Url.Action("AuthenticationCallback"));
        }

        [AllowAnonymous]
        public ActionResult AuthenticationCallback()
        {
            var result = OAuthWebSecurity.VerifyAuthentication();
            if (result.IsSuccessful)
            {
                int uniqueUserID = int.Parse(result.ProviderUserId);
                if (Users.GetUserByVkId(uniqueUserID) == null)
                {
                    User newUser = new User();
                    newUser.PasswordHash = null;
                    newUser.Email = result.ExtraData["email"];
                    newUser.LastActivity = DateTime.Now;
                    newUser.Nickname = result.UserName;
                    newUser.VkId = uniqueUserID;
                    newUser.VkAccessToken = result.ExtraData["accessToken"];
                    if (Users.Add(newUser) == false)
                    {
                        NotificationManager.Instance.Add("Can't add user data to DB, perhaps, we already have user with this e-mail", NotificationType.Error);
                        return RedirectToAction("Index", "Home");
                    }
                }

                if (Auth.Login(uniqueUserID, result.ExtraData["email"]) == null)
                {
                    NotificationManager.Instance.Add("Can't authenticate user with provided data", NotificationType.Error);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            NotificationManager.Instance.Add("Can't complete VK authentication", NotificationType.Error);
            return RedirectToAction("Index", "Home");
        }
    }
}

Munchkin Online/Controllers/FriendsController.cs
using Munchkin_Online.Core.Auth;
using Munchkin_Online.Core.Database;
using Munchkin_Online.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Munchkin_Online.Controllers
{
    [Authorize]
    public class FriendsController : Controller
    {
        public ActionResult List()
        {
            return PartialView(CurrentUser.Instance.Current.Friends);
        }

        [HttpPost]
        public ActionResult Search()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult FriendPlateList(string name)
        {
            using (UserRepository repo = new UserRepository())
            {
                return PartialView(repo.GetPotentialFriendListByNickname(name, CurrentUser.Instance.Current));
            }
        }

        public string ManageFriend(Guid? id)
        {
            using (UserRepository repo = new UserRepository())
            {
                User curUser = repo.GetUser(CurrentUser.Instance.Current.Id);
                if (Request.HttpMethod == "PUT")
                    curUser.Friends.Add(repo.GetUser(id.Value));
                else if (Request.HttpMethod == "DELETE")
                    curUser.Friends.Remove(repo.GetUser(id.Value));
                else
                {
                    Response.StatusCode = 404;
                    return "";
                }
                repo.ForceSaveChanges();
                return "success";
            }
        }
    }
}

Munchkin Online/Controllers/ProfileController.cs
using Munchkin_Online.Core.Auth;
using Munchkin_Online.Core.Database;
using Munchkin_Online.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Munchkin_Online.Controllers
{
    public class ProfileController : Controller
    {
        public ActionResult Index(Guid? profileId)
        {
            if (profileId.HasValue)
            {
                UserRepository repo = new UserRepository();
                User user = repo.GetUser(profileId.Value);

                if (user != null)
                    return View(user);
            }

            //todo: add proper error message (Profile not found)
            Response.StatusCode = 404;
            return new EmptyResult();
        }

        public ActionResult TopPlayers()
        {
            UserRepository repo = new UserRepository();
            return View(repo.GetTopPlayers());
        }
    }

    
}

Munchkin Online/Views/Shared/_Layout.cshtml
@using Munchkin_Online.Core
@using Munchkin_Online.Core.Auth
@using Munchkin_Online.Models

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <meta HTTP-EQUIV="Pragma" CONTENT="no-cache">
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/js/Core")
        @Scripts.Render("~/js/Friends")
        <title>@ViewBag.Title</title>
    </head>
    <body>
        <div class="wrapper">
            <header>
                <h1>Munchkin!</h1>
                <div class="moto">@Html.Raw(MotoImporter.GetMoto())</div>
                <div class="auth-bar-container">
                    <div class="auth-bar">
                        @if(!Request.IsAuthenticated)
                        {
                            @Html.ActionLink("Регистрация", "Register", "Accounts")
                        }
                        else
                        {
                            @("Привет, ") @Html.ActionLink(CurrentUser.Instance.Current.Nickname, CurrentUser.Instance.Current.Id.ToString("N"), "Profile") @(" / ")@Html.ActionLink("Выход", "Logout", "Accounts")
                        }
                    </div>
                    @if(!Request.IsAuthenticated)
                    {
                        <div class="auth">
                            <div class="container">
                                @using (Html.BeginForm("Login", "Accounts"))
                                {
                                    <input type="text" name="Email" placeholder="Email"/>
                                    <input type="password" name="Password" placeholder="Password"/>
                                    <input type="submit" value="Вход"/>
                                }
                            </div>
                            <div class="social">
                                <a class="vk" href="/accounts/VKLogin"></a>
                                <span>Connect!</span>
                                <a class="twitter"></a>
                            </div>
                            <div class="control"></div>
                        </div>
                    }
                    else
                    {
                        <div class="friends">
                            <div id="friend-list" class="container" hidden>
                                @Html.Action("List", "Friends")
                            </div>
                            <div class="add-friend">Add friend</div>
                            <div class="control down"></div>
                        </div>
                    }
                </div>
            </header>
            <aside>
                <ul class="nav">
                    <li><a @(ViewBag.pageID == PageID.PAGE_MAIN ? "class=current" : "") href="/">Main&nbsp;page</a>
                    <li><a @(ViewBag.pageID == PageID.PAGE_RULES ? "class=current" : "") href="/rules/">Game&nbsp;rules</a>
                    <li><a @(ViewBag.pageID == PageID.PAGE_FIND_GAME ? "class=current" : "") href="/game/find">Find&nbsp;game</a>
                    <li><a @(ViewBag.pageID == PageID.PAGE_LOBBY ? "class=current" : "") href="/lobby/">Private&nbsp;lobby</a>
                </ul>
            </aside>
            <div class="main-block">
                @RenderBody()
            </div>
        </div>
        <footer>
            Все права защищены шариатом <br/>
            <span class="small">
                Товарный знак "Мамка Влада" принадлежит соответствующим владельцам.
            </span>
        </footer>
        <div id="blackout"></div>
        <div class="sticky-info">
            <div class="body">
                <p></p>
            </div>
            <div class="scroll left"></div>
            <div class="scroll center"></div>
            <div class="scroll right"></div>
        </div>
        <div class="notification">
            <div class="body">
                <p></p>
            </div>
            <div class="scroll left"></div>
            <div class="scroll center"></div>
            <div class="scroll right"></div>
        </div>
        <div id="popup-container" hidden></div>
        @Scripts.Render("~/js/LongPool")
        @RenderSection("scripts", required: false)
    </body>
</html>